local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', 'C-p', builtin.git.files, {})
vim.keymap.set('n', '<leader>ps', funtion()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
